INSERT INTO
    user (
        name,
        surname,
        email,
        password,
        dni,
        cuit,
        birthday,
        gender,
        city
    )
VALUES
    (
        'Juan',
        'Perez',
        'juan@example.com',
        'password123',
        '12345678',
        '1122334455',
        '1990-05-15',
        0,
        82084
    ),
    (
        'Maria',
        'Gomez',
        'maria@example.com',
        'securepass',
        '98765432',
        '5544332211',
        '1985-08-20',
        1,
        82084
    ),
    (
        'Carlos',
        'Rodriguez',
        'carlos@example.com',
        'pass123',
        '56789012',
        '9988776655',
        '1982-03-10',
        0,
        82084
    ),
    (
        'Laura',
        'Fernandez',
        'laura@example.com',
        'laurapass',
        '34567890',
        '3344556677',
        '1995-11-25',
        1,
        82084
    ),
    (
        'Pedro',
        'Lopez',
        'pedro@example.com',
        'securepassword',
        '87654321',
        '1122334455',
        '1988-07-08',
        0,
        82084
    ),
    (
        'Ana',
        'Martinez',
        'ana@example.com',
        'pass456',
        '23456789',
        '9988776655',
        '1992-01-30',
        1,
        82084
    ),
    (
        'Gabriel',
        'Diaz',
        'gabriel@example.com',
        'gabrielpass',
        '78901234',
        '3344556677',
        '1980-09-18',
        0,
        82084
    ),
    (
        'Sofia',
        'Ramos',
        'sofia@example.com',
        'sofiapass',
        '45678901',
        '1122334455',
        '1993-04-05',
        1,
        82084
    ),
    (
        'Daniel',
        'Hernandez',
        'daniel@example.com',
        'password789',
        '12389045',
        '9988776655',
        '1987-12-12',
        0,
        82084
    ),
    (
        'Elena',
        'Garcia',
        'elena@example.com',
        'elenapass',
        '67890123',
        '3344556677',
        '1996-06-22',
        1,
        82084
    ),
    (
        'Alejandro',
        'Silva',
        'alejandro@example.com',
        'alepass',
        '89012345',
        '1122334455',
        '1983-02-14',
        0,
        82084
    ),
    (
        'Luisa',
        'Vargas',
        'luisa@example.com',
        'luisapass',
        '34567890',
        '9988776655',
        '1994-10-03',
        1,
        82084
    ),
    (
        'Roberto',
        'Torres',
        'roberto@example.com',
        'robertopass',
        '56789012',
        '3344556677',
        '1986-08-07',
        0,
        82084
    ),
    (
        'Carmen',
        'Mendoza',
        'carmen@example.com',
        'carmenpass',
        '12345678',
        '1122334455',
        '1991-03-28',
        1,
        82084
    ),
    (
        'Javier',
        'Rojas',
        'javier@example.com',
        'javierpass',
        '98765432',
        '9988776655',
        '1984-05-11',
        0,
        82084
    ),
    (
        'Silvia',
        'Santos',
        'silvia@example.com',
        'silviapass',
        '56789012',
        '3344556677',
        '1997-09-14',
        1,
        82084
    ),
    (
        'Miguel',
        'Fuentes',
        'miguel@example.com',
        'miguelpass',
        '23456789',
        '1122334455',
        '1989-12-09',
        0,
        82084
    ),
    (
        'Beatriz',
        'Ortega',
        'beatriz@example.com',
        'beatrizpass',
        '87654321',
        '9988776655',
        '1998-04-02',
        1,
        82084
    ),
    (
        'Felipe',
        'Perez',
        'felipe@example.com',
        'felipepass',
        '34567890',
        '3344556677',
        '1981-06-17',
        0,
        82084
    ),
    (
        'Monica',
        'Gutierrez',
        'monica@example.com',
        'monicapass',
        '12345678',
        '1122334455',
        '1990-11-23',
        0,
        82084
    );

INSERT INTO
    doctor (
        registration,
        title,
        durationMeeting,
        priceMeeting,
        verified,
        employmentDate,
        userId,
        planId,
        description
    )
VALUES
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        30,
        3000,
        1,
        '1998-04-08',
        2,
        1,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        60,
        140,
        0,
        '2009-09-18',
        4,
        1,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        40,
        110,
        1,
        '2009-09-18',
        5,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        30,
        60,
        1,
        '2009-09-18',
        6,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        30,
        80,
        1,
        '2009-09-18',
        7,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        20,
        80,
        1,
        '2009-09-18',
        8,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        45,
        140,
        1,
        '2011-03-05',
        9,
        1,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        40,
        170,
        1,
        '2017-10-12',
        10,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        30,
        95,
        1,
        '2019-06-22',
        11,
        1,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        45,
        125,
        1,
        '2018-01-14',
        12,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        40,
        155,
        1,
        '2013-05-03',
        13,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        30,
        100,
        1,
        '2012-11-28',
        14,
        1,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        45,
        130,
        1,
        '2014-07-17',
        15,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        40,
        160,
        1,
        '2016-02-09',
        16,
        1,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        30,
        110,
        1,
        '2010-06-04',
        17,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        45,
        140,
        1,
        '2011-12-21',
        18,
        1,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        40,
        170,
        1,
        '2015-08-08',
        19,
        2,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    ),
    (
        'dsamdp-dsad-dsadf.pdf',
        'dmsadpo-dmsapod-dsda.pdf',
        30,
        95,
        1,
        '2017-03-30',
        20,
        1,
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe possimus ad ea nisi iusto temporibus cum, voluptatibus fugiat magnam maiores consequatur, architecto harum dignissimos deleniti eius, quisquam natus minus quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel aspernatur repellendus, eos, cupiditate consectetur eum modi laboriosam vero officia quibusdam earum tenetur omnis similique autem ab facilis aut. Laborum, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, deleniti deserunt iste corporis possimus, eos facere quis quidem, consequuntur sapiente quae! Quidem repellendus ab nemo praesentium. Sequi modi quis et!"
    );

INSERT INTO
    doctor_specialities_speciality (
        doctorId,
        specialityId
    )
VALUES
(1, 1),
(2, 2),
(3, 1);